
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgvhqbrduldioozggthd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndmhxYnJkdWxkaW9vemdndGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjM0ODYsImV4cCI6MjA1OTYzOTQ4Nn0.ZTMTP0G-zr2z64QbvIt4kPsmXLU84rDgtIi53RvIaFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
